layout_spectrum: 0.06383074
typography_spectrum: 0.2816653
color:
  saturation: 0.5645207
  lightness: 0.3035239
  brandStrength: 0.2599747
  rhythmicContrast: 0.06870053
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: chrisjones
